# ==============================================================================
# Makefile for the Sharded Blockchain MPI Project
#
# This Makefile automates the build process for the C++/MPI simulation
# based on the project structure defined in 'STRUCTURE.md'.
#
# It supports:
#   - Out-of-source builds (all artifacts go into 'build/')
#   - Automatic dependency tracking (recompiles if headers change)
#   - Building the main simulation ('make all')
#   - Building test executables ('make tests')
#   - Running the simulation with configurable parameters ('make run')
#   - Cleaning all build artifacts ('make clean')
#
# Based on project documents:
# - PROPOSAL.md: Specifies C++ and MPI.
# - IMPLEMENTATION_PLAN.md: Specifies 'mpic++' and build/test targets.
# - STRUCTURE.md: Defines the src, include, build, and tests layout.
# ==============================================================================

# --- Configuration ---

# Compiler: Use the MPI C++ wrapper, as required by the project.
CXX := mpic++

# Compiler Flags:
# -std=c++17: Use modern C++.
# -g:         Include debug symbols (essential for development/testing).
# -Wall -Wextra: Enable all useful warnings.
# -Iinclude:  Tell the compiler where to find our headers (e.g., "sbmpi/core/node.h").
# -MMD -MP:   Generate dependency files (.d) for automatic header tracking.
CXXFLAGS := -std=c++17 -g -Wall -Wextra -fopenmp -Iinclude -MMD -MP -Isecp256k1/include -Ijson/single_include

# Linker Flags: (MPI wrapper handles most linking)
LDFLAGS := secp256k1/local/lib/libsecp256k1.a -lcrypto

# --- Directories ---
BUILD_DIR   := build
SRC_DIR     := src
INCLUDE_DIR := include
TEST_DIR    := tests

# --- Target ---
# The main simulation executable
TARGET := $(BUILD_DIR)/main

# --- Source Files (Auto-discovery) ---

# Find all .cpp files in the 'src' subdirectories (core, consensus, etc.)
# These are the "library" files.
LIB_SRCS := $(shell find $(SRC_DIR)/core $(SRC_DIR)/consensus $(SRC_DIR)/network $(SRC_DIR)/util -name '*.cpp')

# Find the main entry point
MAIN_SRC := $(SRC_DIR)/main.cpp

# Find all test source files
TEST_SRCS := $(shell find $(TEST_DIR) -name '*.cpp')

# --- Object Files ---

# Convert source file paths to object file paths in the 'build/obj' directory.
# This creates a parallel directory structure (e.g., build/obj/core/node.o)
LIB_OBJS := $(patsubst $(SRC_DIR)/%.cpp, $(BUILD_DIR)/obj/%.o, $(LIB_SRCS))
MAIN_OBJ := $(patsubst $(SRC_DIR)/%.cpp, $(BUILD_DIR)/obj/%.o, $(MAIN_SRC))

# --- Test Targets ---

# Define the target executable names for tests
# (e.g., build/test_pbft, build/test_sharding)
TEST_TARGETS := $(patsubst $(TEST_DIR)/%.cpp, $(BUILD_DIR)/%, $(TEST_SRCS))

# --- Dependency Files ---

# List of dependency files (.d) that will be generated by the compiler
DEPS := $(patsubst $(SRC_DIR)/%.cpp, $(BUILD_DIR)/obj/%.d, $(LIB_SRCS) $(MAIN_SRC))

# ==============================================================================
# MAIN BUILD RULES
# ==============================================================================

# Default target: Build the main simulation executable.
.PHONY: all
all: $(TARGET)

# Rule to link the main executable ('build/main')
$(TARGET): $(MAIN_OBJ) $(LIB_OBJS)
	@echo "Linking main target: $@"
	@mkdir -p $(@D) # Ensure the 'build' directory exists
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

# Pattern rule to compile .cpp files from 'src' into .o files in 'build/obj'
# This rule handles all our main and library source files.
$(BUILD_DIR)/obj/%.o: $(SRC_DIR)/%.cpp
	@echo "Compiling: $<"
	@mkdir -p $(@D) # Ensure the 'build/obj/core', etc. directories exist
	$(CXX) $(CXXFLAGS) -c -o $@ $<

# ==============================================================================
# TEST BUILD RULES
# ==============================================================================

# Target to build all test executables.
.PHONY: tests
tests: $(TEST_TARGETS)

# Pattern rule to build a test executable.
# e.g., 'build/test_pbft' depends on 'tests/test_pbft.cpp' and all LIB_OBJS
# This rule compiles the test source and links it against the compiled library
# objects in a single step.
$(BUILD_DIR)/%: $(TEST_DIR)/%.cpp $(LIB_OBJS)
	@echo "Building test: $@"
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) -o $@ $< $(LIB_OBJS) $(LDFLAGS)

# ==============================================================================
# RUN RULES
# ==============================================================================

# Configurable parameters for 'make run'
NP   ?= 8
ARGS ?= --shards 6 --transactions 100000 --run-id 1 --seed 42 --transaction-size 256 --faults 0.2 -v 1

# Rule to run the main simulation.
# Example: make run NP=64 ARGS="--shards 8 --transactions 10000"
# [cite: IMPLEMENTATION_PLAN.md]
.PHONY: run
run: all
	@echo "Running simulation on $(NP) processes..."
	mpirun -np $(NP) $(TARGET) $(ARGS)

# Rule to run the test suite.
# Runs each test executable with 4 processes by default.
.PHONY: run_tests
run_tests: tests
	@echo "Running test suite..."
	$(foreach test, $(TEST_TARGETS), \
		echo "--- Running $(test) ---"; \
		mpirun -np 4 $(test); \
	)

# ==============================================================================
# CLEANUP
# ==============================================================================

# Rule to remove all build artifacts.
.PHONY: clean
clean:
	@echo "Cleaning up build artifacts..."
	rm -rf $(BUILD_DIR)

# ==============================================================================
# DEPENDENCY HANDLING
# ==============================================================================

# Include the auto-generated dependency files.
# This makes the build system smart: changing a .h file will now
# trigger a recompilation of the .cpp files that include it.
-include $(DEPS)