/**
 * @file transaction.h
 * @brief Defines the core Transaction data structure.
 *
 * @headerfile transaction.h
 *
 * @details
 * The corresponding transaction.cpp will implement the serialization and
 * deserialization methods. This class defines the fundamental unit of work
 * in the blockchain simulation.
 *
 * **MPI Interaction:**
 * This class is not just a data struct; it's a "message." MPI can only
 * send contiguous blocks of memory (byte buffers). The `serialize()`
 * method will pack the Transaction object into a `std::vector<char>`
 * (or a raw char*) for `MPI_Send`. The `deserialize()` method will
 * unpack that byte buffer back into a `Transaction` object after `MPI_Recv`
 *. This is critical for distributing
 * transactions from the root node to the shards.
 *
 * It is aggregated by the `Block` class and generated by the root process
 * in `main.cpp`.
 */

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace sbmpi
{
  namespace core
  {

    /**
     * @struct Transaction
     * @brief Represents a single transaction in the system.
     */
    struct Transaction {
      uint64_t id;
      uint64_t timestamp;
      uint32_t sender_id;
      uint32_t receiver_id;
      double   value;

      /**
       * @brief Serializes the Transaction into a byte buffer for MPI.
       * @return A vector of chars representing the serialized object.
       */
      std::vector<char> serialize() const;

      /**
       * @brief Deserializes a byte buffer into this Transaction object.
       * @param buffer The byte buffer received from MPI.
       */
      void deserialize(const std::vector<char>& buffer);

      /**
       * @brief Creates a custom MPI Datatype for this struct.
       *
       * An alternative to serialization is to create a custom MPI_Datatype.
       * This function would define that type, but serialization is
       * often more flexible.
       */
      // static void createMpiType(MPI_Datatype* mpi_transaction_type);
      std::string getHash() const;
    };

    /**
     * @brief Factory function to create a vector of mock transactions.
     * @param count The number of transactions to create.
     * @return A vector of mock Transaction objects.
     */
    std::vector<Transaction> createMockTransactions(size_t count);

  }  // namespace core
}  // namespace sbmpi