#ifndef SBMPI_MICRO_BLOCK_H
#define SBMPI_MICRO_BLOCK_H

#include "block.h"

/**
 * @file micro_block.h
 * @brief Defines the MicroBlock class, a concrete implementation of a block created by a shard.
 *
 * A MicroBlock is generated by a single shard committee after reaching consensus
 * on a set of transactions. It contains the transactions validated by the shard
 * and is sent to the final committee for aggregation into a MacroBlock.
 */

class MicroBlock : public Block {
public:
    // The ID of the shard that produced this block.
    int shardId;

    /**
     * @brief Default constructor for MicroBlock.
     */
    MicroBlock();

    /**
     * @brief Constructs a MicroBlock with a specified shard ID.
     *
     * @param shardId The ID of the originating shard.
     */
    MicroBlock(int shardId);

    /**
     * @brief Gets the type of the block.
     *
     * @return The string "MicroBlock".
     */
    std::string getType() const override;

    /**
     * @brief Serializes the MicroBlock into a byte vector.
     *
     * @return A std::vector<char> containing the serialized block data.
     */
    std::vector<char> serialize() const override;

    /**
     * @brief Deserializes a byte vector into a MicroBlock object.
     *
     * @param data The byte vector to deserialize.
     */
    void deserialize(const std::vector<char>& data) override;
};

#endif // SBMPI_MICRO_BLOCK_H